### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Removed redundant code in the project. 
2. Fixed naming convention. 
3. General code improvements.

### CODE REVIEW

**Comment by AleksandarDev** [comment]
@MCCshreyas Thanks for the PR.

Actually we prefer `this` for class field/property/method access to differentiate from method arguments. We also don't use `_` prefix for private fields. 

We'll accept this PR if you revert these changes and push to another branch so that we can release this with next feature/patch (as we want to keep the `master` branch in sync with the releases).

Also, do you have any suggestions on how can we document the code conventions?

**Comment by ShreyasJejurkar** [comment]
Ok. To which branch should I push my branch? There is an only master branch in your repo. 

You can have a Wiki telling your repo specific code convention so that developers can look at it before creating PR. 
BTW I wondered why you don't use _ prefix for private fields, its one of the famous and most used code convention around the world.

**Comment by AleksandarDev** [comment]
@MCCshreyas Feel free to contribute to our wiki.

We try to follow the Microsoft .NET/C# code conventions:
[C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
[General Naming Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions)

**Comment by AleksandarDev** [comment]
Closed for not following code and naming conventions

- [C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
- [General Naming Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/general-naming-conventions)

**Pull request closed without merging**
